_country_code_to_name_map = {
    'AC': ['Ascension Island', 'ascension'],
    'AD': ['Andorra'],
    'AE': ['United Arab Emirates', 'uae', 'emirates'],
    'AF': ['Afghanistan'],
    'AG': ['Antigua and Barbuda'],
    'AI': ['Anguilla'],
    'AL': ['Albania'],
    'AM': ['Armenia'],
    'AO': ['Angola'],
    'AQ': ['Antarctica'],
    'AR': ['Argentina'],
    'AS': ['American Samoa'],
    'AT': ['Austria'],
    'AU': ['Australia', 'aus'],
    'AW': ['Aruba'],
    'AX': ['Aland Islands', 'aland', 'alands'],
    'AZ': ['Azerbaijan'],
    'BA': ['Bosnia and Herzegovina', 'bosnia', 'bih'],
    'BB': ['Barbados'],
    'BD': ['Bangladesh'],
    'BE': ['Belgium'],
    'BF': ['Burkina Faso'],
    'BG': ['Bulgaria'],
    'BH': ['Bahrain'],
    'BI': ['Burundi'],
    'BJ': ['Benin'],
    'BM': ['Bermuda'],
    'BN': ['Brunei Darussalam', 'brunei'],
    'BO': ['Bolivia'],
    'BQ-BO': ['Bonaire'],
    'BQ-SE': ['Sint Eustatius', 'st eustatius'],
    'BQ-SA': ['Saba'],
    'BR': ['Brazil'],
    'BS': ['The Bahamas', 'bahamas'],
    'BT': ['Bhutan'],
    'BW': ['Botswana'],
    'BY': ['Belarus'],
    'BZ': ['Belize'],
    'CA': ['Canada'],
    'CC': ['Cocos (Keeling) Islands', 'cocos islands', 'keeling islands', 'cocos', 'keeling'],
    'CD': ['Democratic Republic of the Congo', 'drc', 'dr congo'],
    'CF': ['Central African Republic', 'car', 'central africa'],
    'CG': ['Republic of the Congo', 'roc'],
    'CH': ['Switzerland'],
    'CI': ['Cote d\'Ivoire', 'ivory coast'],
    'CK': ['Cook Islands', 'cook'],
    'CL': ['Chile'],
    'CM': ['Cameroon'],
    'CN': ['China'],
    'CO': ['Colombia'],
    'CR': ['Costa Rica'],
    'CU': ['Cuba'],
    'CV': ['Cape Verde', 'cabo verde'],
    'CW': ['Curacao'],
    'CX': ['Christmas Island', 'christmas'],
    'CY': ['Cyprus'],
    'CZ': ['Czech Republic', 'czechia', 'czech'],
    'DE': ['Germany'],
    'DJ': ['Djibouti'],
    'DK': ['Denmark'],
    'DM': ['Dominica'],
    'DO': ['Dominican Republic', 'dominican'],
    'DZ': ['Algeria'],
    'EC': ['Ecuador'],
    'EE': ['Estonia'],
    'EG': ['Egypt'],
    'EH': ['Western Sahara', 'Sahrawi Arab Democratic Republic', 'sahrawi republic', 'sahrawi'],
    'ER': ['Eritrea'],
    'ES': ['Spain'],
    'ET': ['Ethiopia'],
    'FI': ['Finland'],
    'FJ': ['Fiji'],
    'FK': ['Falkland Islands (Malvinas)', 'falklands', 'falkland', 'falkland islands', 'malvinas'],
    'FM': ['Micronesia'],
    'FO': ['Faroe Islands', 'faroe'],
    'FR': ['France'],
    'GA': ['Gabon'],
    'GB': ['United Kingdom', 'uk'],
    'GB-ENG': ['England'],
    'GB-NIR': ['Northern Ireland', 'ni'],
    'GB-SCT': ['Scotland'],
    'GB-WLS': ['Wales'],
    'GD': ['Grenada'],
    'GE': ['Georgia'],
    'GF': ['French Guiana'],
    'GG': ['Bailiwick of Guernsey', 'guernsey'],
    'GH': ['Ghana'],
    'GI': ['Gibraltar'],
    'GL': ['Greenland'],
    'GM': ['The Gambia', 'gambia'],
    'GN': ['Guinea'],
    'GP': ['Guadeloupe'],
    'GQ': ['Equatorial Guinea'],
    'GR': ['Greece'],
    'GS': ['South Georgia and the South Sandwich Islands', 'sandwich'],
    'GT': ['Guatemala'],
    'GU': ['Guam'],
    'GW': ['Guinea-Bissau'],
    'GY': ['Guyana'],
    'HK': ['Hong Kong'],
    'HN': ['Honduras'],
    'HR': ['Croatia', 'hrv', 'cro'],
    'HT': ['Haiti'],
    'HU': ['Hungary'],
    'IC': ['Canary Islands', 'canary'],
    'ID': ['Indonesia'],
    'IE': ['Ireland'],
    'IL': ['Israel'],
    'IM': ['Isle of Man'],
    'IN': ['India'],
    'IO': ['British Indian Ocean Territory', 'biot'],
    'IQ': ['Iraq'],
    'IR': ['Islamic Republic of Iran', 'iran'],
    'IS': ['Iceland'],
    'IT': ['Italy'],
    'JE': ['Jersey'],
    'JM': ['Jamaica'],
    'JO': ['Jordan'],
    'JP': ['Japan', 'weebland'],
    'KE': ['Kenya'],
    'KG': ['Kyrgyzstan', 'kyrg'],
    'KH': ['Cambodia'],
    'KI': ['Kiribati'],
    'KM': ['Comoros'],
    'KN': ['Saint Kitts and Nevis', 'st kitts and nevis'],
    'KP': ['North Korea', 'dprk', 'best korea', 'nk'],
    'KR': ['South Korea', 'sk'],
    'KW': ['Kuwait'],
    'KY': ['Cayman Islands', 'cayman', 'caymans'],
    'KZ': ['Kazakhstan'],
    'LA': ['Laos'],
    'LB': ['Lebanon'],
    'LC': ['Saint Lucia', 'st lucia'],
    'LI': ['Liechtenstein'],
    'LK': ['Sri Lanka'],
    'LR': ['Liberia'],
    'LS': ['Lesotho'],
    'LT': ['Lithuania'],
    'LU': ['Luxembourg', 'lux'],
    'LV': ['Latvia'],
    'LY': ['Libya'],
    'MA': ['Morocco'],
    'MC': ['Monaco'],
    'MD': ['Moldova'],
    'ME': ['Montenegro'],
    'MG': ['Madagascar'],
    'MH': ['Marshall Islands', 'marshall'],
    'MK': ['North Macedonia', 'macedonia'],
    'ML': ['Mali'],
    'MM': ['Myanmar', 'burma'],
    'MN': ['Mongolia', 'mongol'],
    'MO': ['Macau', 'macao'],
    'MP': ['Northern Mariana Islands', 'northern mariana', 'northern marianas'],
    'MQ': ['Martinique'],
    'MR': ['Mauritania'],
    'MS': ['Montserrat'],
    'MT': ['Malta'],
    'MU': ['Mauritius'],
    'MV': ['Maldives'],
    'MW': ['Malawi'],
    'MX': ['Mexico', 'mex'],
    'MY': ['Malaysia'],
    'MZ': ['Mozambique'],
    'NA': ['Namibia'],
    'NC': ['New Caledonia'],
    'NE': ['Niger'],
    'NF': ['Norfolk Island', 'norfolk'],
    'NG': ['Nigeria'],
    'NI': ['Nicaragua'],
    'NL': ['Netherlands', 'the netherlands', 'nl'],
    'NO': ['Norway', 'Svalbard and Jan Mayen', 'svalbard', 'norge'],
    'NP': ['Nepal'],
    'NR': ['Nauru'],
    'NU': ['Niue'],
    'NZ': ['New Zealand', 'nz', 'kiwiland'],
    'OM': ['Oman'],
    'PA': ['Panama'],
    'PE': ['Peru'],
    'PF': ['French Polynesia'],
    'PG': ['Papua New Guinea', 'papa johns'],
    'PH': ['Philippines', 'the philippines'],
    'PK': ['Pakistan'],
    'PL': ['Poland'],
    'PM': ['Saint Pierre and Miquelon', 'saint pierre', 'st pierre'],
    'PN': ['Pitcairn', 'pitcairn islands', 'pitcairns'],
    'PR': ['Puerto Rico'],
    'PS': ['Palestine'],
    'PT': ['Portugal'],
    'PW': ['Palau'],
    'PY': ['Paraguay'],
    'QA': ['Qatar'],
    'RO': ['Romania'],
    'RS': ['Serbia', 'enemies'],
    'RU': ['russia', 'russian federation', 'ru', 'cccp'],
    'RW': ['Rwanda'],
    'SA': ['Saudi Arabia', 'saudi'],
    'SB': ['Solomon Islands', 'solomon', 'solomons'],
    'SC': ['Seychelles'],
    'SD': ['Sudan'],
    'SE': ['Sweden'],
    'SG': ['Singapore'],
    'SH': ['Saint Helena, Ascension and Tristan da Cunha', 'st helena', 'saint helena'],
    'SI': ['Slovenia'],
    'SK': ['Slovakia'],
    'SL': ['Sierra Leone'],
    'SM': ['San Marino'],
    'SN': ['Senegal'],
    'SO': ['Somalia'],
    'SR': ['Suriname'],
    'SS': ['South Sudan'],
    'ST': ['Sao Tome and Principe', 'sao tome'],
    'SV': ['El Salvador'],
    'SX': ['Sint Maarten (Dutch part)', 'sint maarten', 'st martin', 'saint martin'],
    'SY': ['Syria'],
    'SZ': ['Swaziland', 'eswatini'],
    'TA': ['Tristan da Cunha'],
    'TC': ['Turks and Caicos Islands', 'turks and caicos'],
    'TD': ['Chad'],
    'TF': ['French Southern and Antarctic Lands', 'French Southern Territories', 'French Southern Lands', 'fst', 'fsal',
           'taaf'],
    'TG': ['Togo'],
    'TH': ['Thailand'],
    'TJ': ['Tajikistan', 'tajik'],
    'TK': ['Tokelau'],
    'TL': ['Timor-Leste', 'East Timor'],
    'TM': ['Turkmenistan', 'turkmen'],
    'TN': ['Tunisia'],
    'TO': ['Tonga'],
    'TR': ['Turkey', 'turkiye'],
    'TT': ['Trinidad and Tobago'],
    'TV': ['Tuvalu'],
    'TW': ['Taiwan'],
    'TZ': ['Tanzania'],
    'UA': ['Ukraine'],
    'UG': ['Uganda'],
    'US': ['United States of Amerca', 'united states', 'america', 'us', 'usa'],
    'UY': ['Uruguay'],
    'UZ': ['Uzbekistan', 'uzbek'],
    'VA': ['Holy See', 'vatican city', 'vatican'],
    'VC': ['Saint Vincent and the Grenadines', 'st vincent', 'saint vincent'],
    'VE': ['Venezuela'],
    'VG': ['British Virgin Islands', 'uk vi', 'british virgin'],
    'VI': ['United States Virgin Islands', 'us virgin islands', 'us vi', 'us virgin'],
    'VN': ['Vietnam'],
    'VU': ['Vanuatu'],
    'WF': ['Wallis and Futuna'],
    'WS': ['Samoa'],
    'XK': ['Kosovo'],
    'YE': ['Yemen'],
    'YT': ['Mayotte'],
    'ZA': ['South Africa'],
    'ZM': ['Zambia'],
    'ZW': ['Zimbabwe'],
}

_country_code_to_capital_map = {
    'AC': ['Georgetown'],
    'AD': ['Andorra la Vella'],
    'AE': ['Abu Dhabi'],
    'AF': ['Kabul'],
    'AG': ['Saint John\'s', 'st johns'],
    'AI': ['The Valley'],
    'AL': ['Tirana'],
    'AM': ['Yerevan'],
    'AO': ['Luanda'],
    'AQ': ['N/A', 'none'],
    'AR': ['Buenos Aires'],
    'AS': ['Pago Pago', 'pagox2'],
    'AT': ['Vienna'],
    'AU': ['Canberra'],
    'AW': ['Oranjestad'],
    'AX': ['Mariehamn'],
    'AZ': ['Baku'],
    'BA': ['Sarajevo'],
    'BB': ['Bridgetown'],
    'BD': ['Dhaka'],
    'BE': ['Brussels'],
    'BF': ['Ouagadougou', 'wagadoga'],
    'BG': ['Sofia'],
    'BH': ['Manama'],
    'BI': ['Gitega'],
    'BJ': ['Porto-Novo', 'Cotonou'],
    'BM': ['Hamilton'],
    'BN': ['Bandar Seri Begawan', 'begawan'],
    'BO': ['Sucre', 'La Paz'],
    'BQ-BO': ['Kralendijk'],
    'BQ-SE': ['Oranjestad'],
    'BQ-SA': ['The Bottom'],
    'BR': ['Brasilia'],
    'BS': ['Nassau'],
    'BT': ['Thimphu'],
    'BW': ['Gaborone'],
    'BY': ['Minsk'],
    'BZ': ['Belmopan'],
    'CA': ['Ottawa'],
    'CC': ['West Island'],
    'CD': ['Kinshasa'],
    'CF': ['Bangui'],
    'CG': ['Brazzaville'],
    'CH': ['Bern'],
    'CI': ['Yamoussoukro'],
    'CK': ['Avarua'],
    'CL': ['Santiago', 'Valparaíso'],
    'CM': ['Yaounde'],
    'CN': ['Beijing'],
    'CO': ['Bogota'],
    'CR': ['San Jose'],
    'CU': ['Havana'],
    'CV': ['Praia'],
    'CW': ['Willemstad'],
    'CX': ['Flying Fish Cove'],
    'CY': ['Nicosia'],
    'CZ': ['Prague'],
    'DE': ['Berlin'],
    'DJ': ['Djibouti'],
    'DK': ['Copenhagen'],
    'DM': ['Roseau'],
    'DO': ['Santo Domingo'],
    'DZ': ['Algiers'],
    'EC': ['Quito'],
    'EE': ['Tallinn'],
    'EG': ['Cairo'],
    'EH': ['El Aaiun'],
    'ER': ['Asmara'],
    'ES': ['Madrid'],
    'ET': ['Addis Ababa'],
    'FI': ['Helsinki'],
    'FJ': ['Suva'],
    'FK': ['Stanley'],
    'FM': ['Palikir'],
    'FO': ['Torshavn'],
    'FR': ['Paris'],
    'GA': ['Libreville'],
    'GB': ['London'],
    'GB-ENG': ['London'],
    'GB-NIR': ['Belfast'],
    'GB-SCT': ['Edinburgh'],
    'GB-WLS': ['Cardiff'],
    'GD': ['Saint George\'s', 'st georges'],
    'GE': ['Tbilisi'],
    'GF': ['Cayenne'],
    'GG': ['Saint Peter Port', 'st peter port'],
    'GH': ['Accra'],
    'GI': ['Gibraltar'],
    'GL': ['Nuuk'],
    'GM': ['Banjul'],
    'GN': ['Conakry'],
    'GP': ['Basse-Terre'],
    'GQ': ['Malabo'],
    'GR': ['Athens'],
    'GS': ['King Edward Point'],
    'GT': ['Guatemala City'],
    'GU': ['Hagatna'],
    'GW': ['Bissau'],
    'GY': ['Georgetown'],
    'HK': ['Hong Kong'],
    'HN': ['Tegucigalpa'],
    'HR': ['Zagreb'],
    'HT': ['Port-au-Prince'],
    'HU': ['Budapest'],
    'IC': ['Las Palmas'],
    'ID': ['Jakarta'],
    'IE': ['Dublin'],
    'IL': ['Jerusalem'],
    'IM': ['Douglas'],
    'IN': ['New Delhi'],
    'IO': ['Diego Garcia'],
    'IQ': ['Baghdad'],
    'IR': ['Tehran'],
    'IS': ['Reykjavik'],
    'IT': ['Rome'],
    'JE': ['Saint Helier', 'st helier'],
    'JM': ['Kingston'],
    'JO': ['Amman'],
    'JP': ['Tokyo'],
    'KE': ['Nairobi'],
    'KG': ['Bishkek'],
    'KH': ['Phnom Penh'],
    'KI': ['Tarawa'],
    'KM': ['Moroni'],
    'KN': ['Basseterre'],
    'KP': ['Pyongyang'],
    'KR': ['Seoul'],
    'KW': ['Kuwait City'],
    'KY': ['George Town'],
    'KZ': ['Astana'],
    'LA': ['Vientiane'],
    'LB': ['Beirut'],
    'LC': ['Castries'],
    'LI': ['Vaduz'],
    'LK': ['Sri Jayawardenepura Kotte', 'kotte', 'Colombo'],
    'LR': ['Monrovia'],
    'LS': ['Maseru'],
    'LT': ['Vilnius'],
    'LU': ['Luxembourg'],
    'LV': ['Riga'],
    'LY': ['Tripoli'],
    'MA': ['Rabat'],
    'MC': ['Monaco'],
    'MD': ['Chisinau'],
    'ME': ['Podgorica'],
    'MG': ['Antananarivo'],
    'MH': ['Majuro'],
    'MK': ['Skopje'],
    'ML': ['Bamako'],
    'MM': ['Naypyidaw'],
    'MN': ['Ulaanbaatar'],
    'MO': ['Macau'],
    'MP': ['Saipan'],
    'MQ': ['Fort-de-France'],
    'MR': ['Nouakchott'],
    'MS': ['Brades'],
    'MT': ['Valletta'],
    'MU': ['Port Louis'],
    'MV': ['Male'],
    'MW': ['Lilongwe'],
    'MX': ['Mexico City'],
    'MY': ['Kuala Lumpur', 'Putrajaya'],
    'MZ': ['Maputo'],
    'NA': ['Windhoek'],
    'NC': ['Noumea'],
    'NE': ['Niamey'],
    'NF': ['Kingston'],
    'NG': ['Abuja'],
    'NI': ['Managua'],
    'NL': ['Amsterdam'],
    'NO': ['Oslo'],
    'NP': ['Kathmandu'],
    'NR': ['Yaren'],
    'NU': ['Alofi'],
    'NZ': ['Wellington'],
    'OM': ['Muscat'],
    'PA': ['Panama City'],
    'PE': ['Lima'],
    'PF': ['Papeete'],
    'PG': ['Port Moresby'],
    'PH': ['Manila'],
    'PK': ['Islamabad'],
    'PL': ['Warsaw'],
    'PM': ['Saint-Pierre', 'st pierre'],
    'PN': ['Adamstown'],
    'PR': ['San Juan'],
    'PS': ['Ramallah'],
    'PT': ['Lisbon'],
    'PW': ['Ngerulmud'],
    'PY': ['Asuncion'],
    'QA': ['Doha'],
    'RO': ['Bucharest'],
    'RS': ['Belgrade'],
    'RU': ['Moscow'],
    'RW': ['Kigali'],
    'SA': ['Riyadh'],
    'SB': ['Honiara'],
    'SC': ['Victoria'],
    'SD': ['Khartoum'],
    'SE': ['Stockholm'],
    'SG': ['Singapore'],
    'SH': ['Jamestown'],
    'SI': ['Ljubljana'],
    'SK': ['Bratislava'],
    'SL': ['Freetown'],
    'SM': ['San Marino'],
    'SN': ['Dakar'],
    'SO': ['Mogadishu'],
    'SR': ['Paramaribo'],
    'SS': ['Juba'],
    'ST': ['Sao Tome'],
    'SV': ['San Salvador'],
    'SX': ['Philipsburg'],
    'SY': ['Damascus'],
    'SZ': ['Mbabane', 'Lobamba'],
    'TA': ['Edinburgh of the Seven Seas'],
    'TC': ['Cockburn Town'],
    'TD': ['N\'Djamena'],
    'TF': ['Port-aux-Francais'],
    'TG': ['Lome'],
    'TH': ['Bangkok'],
    'TJ': ['Dushanbe'],
    'TK': ['Nukunonu'],
    'TL': ['Dili'],
    'TM': ['Ashgabat'],
    'TN': ['Tunis'],
    'TO': ['Nuku\'alofa'],
    'TR': ['Ankara'],
    'TT': ['Port of Spain'],
    'TV': ['Funafuti'],
    'TW': ['Taipei'],
    'TZ': ['Dodoma'],
    'UA': ['Kyiv'],
    'UG': ['Kampala'],
    'US': ['Washington, D.C.', 'washington'],
    'UY': ['Montevideo'],
    'UZ': ['Tashkent'],
    'VA': ['Vatican City'],
    'VC': ['Kingstown'],
    'VE': ['Caracas'],
    'VG': ['Road Town'],
    'VI': ['Charlotte Amalie'],
    'VN': ['Hanoi'],
    'VU': ['Port Vila'],
    'WF': ['Mata-Utu'],
    'WS': ['Apia'],
    'XK': ['Pristina'],
    'YE': ['Sana\'a'],
    'YT': ['Mamoudzou'],
    'ZA': ['Pretoria', 'Bloemfontein', 'Cape Town'],
    'ZM': ['Lusaka'],
    'ZW': ['Harare'],
}

_country_code_to_population_map = {
    'AC': 806,
    'AD': 77265,
    'AE': 9630959,
    'AF': 38928346,
    'AG': 97928,
    'AI': 15003,
    'AL': 2877797,
    'AM': 2963243,
    'AO': 32866268,
    'AQ': 1106,
    'AR': 45195774,
    'AS': 55191,
    'AT': 9006398,
    'AU': 25687041,
    'AW': 106766,
    'AX': 30094,
    'AZ': 10139177,
    'BA': 3280815,
    'BB': 287371,
    'BD': 164689383,
    'BE': 11589623,
    'BF': 20903273,
    'BG': 6948445,
    'BH': 1701583,
    'BI': 11890784,
    'BJ': 12123200,
    'BM': 62278,
    'BN': 437479,
    'BO': 11673029,
    'BQ-BO': 20131,
    'BQ-SE': 3183,
    'BQ-SA': 1947,
    'BR': 212559417,
    'BS': 393244,
    'BT': 771608,
    'BW': 2351625,
    'BY': 9449323,
    'BZ': 397621,
    'CA': 38005238,
    'CC': 544,
    'CD': 89561403,
    'CF': 4829767,
    'CG': 5518092,
    'CH': 8636896,
    'CI': 26378274,
    'CK': 17564,
    'CL': 19116201,
    'CM': 26545863,
    'CN': 1444216107,
    'CO': 50882891,
    'CR': 5094118,
    'CU': 11326616,
    'CV': 555987,
    'CW': 164100,
    'CX': 2072,
    'CY': 1207359,
    'CZ': 10708981,
    'DE': 83240525,
    'DJ': 988000,
    'DK': 5831404,
    'DM': 71991,
    'DO': 10847910,
    'DZ': 43851044,
    'EC': 17643054,
    'EE': 1326535,
    'EG': 102334404,
    'EH': 597339,
    'ER': 3546421,
    'ES': 46754778,
    'ET': 114963588,
    'FI': 5540720,
    'FJ': 896445,
    'FK': 3480,
    'FM': 115021,
    'FO': 48863,
    'FR': 65273511,
    'GA': 2225734,
    'GB': 68207114,
    'GB-ENG': 56489800,
    'GB-NIR': 1881995,
    'GB-SCT': 5463300,
    'GB-WLS': 3152879,
    'GD': 112523,
    'GE': 3989167,
    'GF': 298682,
    'GG': 67052,
    'GH': 31072940,
    'GI': 33691,
    'GL': 56770,
    'GM': 2416668,
    'GN': 13132795,
    'GP': 400132,
    'GQ': 1402985,
    'GR': 10423054,
    'GS': 30,
    'GT': 17915568,
    'GU': 168775,
    'GW': 1967998,
    'GY': 786552,
    'HK': 7496981,
    'HN': 9904608,
    'HR': 4105267,
    'HT': 11402528,
    'HU': 9660351,
    'IC': 2153389,
    'ID': 273523621,
    'IE': 4994724,
    'IL': 9216900,
    'IM': 85032,
    'IN': 1380004385,
    'IO': 4000,
    'IQ': 40222493,
    'IR': 83992953,
    'IS': 343599,
    'IT': 60244639,
    'JE': 108239,
    'JM': 2961167,
    'JO': 10203134,
    'JP': 126476458,
    'KE': 53771300,
    'KG': 6524191,
    'KH': 16718965,
    'KI': 119446,
    'KM': 869601,
    'KN': 53199,
    'KP': 25778816,
    'KR': 51269185,
    'KW': 4270571,
    'KY': 65720,
    'KZ': 18776707,
    'LA': 7275556,
    'LB': 6825442,
    'LC': 183629,
    'LI': 38128,
    'LK': 21413249,
    'LR': 5057681,
    'LS': 2142249,
    'LT': 2722289,
    'LU': 634814,
    'LV': 1886202,
    'LY': 6871287,
    'MA': 36910560,
    'MC': 39242,
    'MD': 2657637,
    'ME': 622359,
    'MG': 27691019,
    'MH': 59194,
    'MK': 2083459,
    'ML': 20250834,
    'MM': 54409794,
    'MN': 3278292,
    'MO': 649335,
    'MP': 57559,
    'MQ': 375265,
    'MR': 4649658,
    'MS': 4922,
    'MT': 514564,
    'MU': 1271768,
    'MV': 540542,
    'MW': 19129955,
    'MX': 128932753,
    'MY': 32365998,
    'MZ': 31255435,
    'NA': 2540905,
    'NC': 271960,
    'NE': 24206636,
    'NF': 2188,
    'NG': 206139587,
    'NI': 6624554,
    'NL': 17441139,
    'NO': 5421241,
    'NP': 29136808,
    'NR': 10834,
    'NU': 1626,
    'NZ': 5084300,
    'OM': 5106622,
    'PA': 4314768,
    'PE': 32971846,
    'PF': 280904,
    'PG': 8947027,
    'PH': 109581085,
    'PK': 220892331,
    'PL': 38386000,
    'PM': 5794,
    'PN': 47,
    'PR': 3193694,
    'PS': 5101414,
    'PT': 10196709,
    'PW': 18094,
    'PY': 7132530,
    'QA': 2881053,
    'RO': 19237691,
    'RS': 8737371,
    'RU': 145912025,
    'RW': 12952218,
    'SA': 34813867,
    'SB': 686878,
    'SC': 98347,
    'SD': 43849269,
    'SE': 10353442,
    'SG': 5850342,
    'SH': 6071,
    'SI': 2100126,
    'SK': 5456362,
    'SL': 7976983,
    'SM': 33931,
    'SN': 16743927,
    'SO': 15893219,
    'SR': 586632,
    'SS': 11193725,
    'ST': 219159,
    'SV': 6486201,
    'SX': 42965,
    'SY': 17500658,
    'SZ': 1160164,
    'TA': 264,
    'TC': 38717,
    'TD': 16425864,
    'TF': 400,
    'TG': 8278724,
    'TH': 69799978,
    'TJ': 9537642,
    'TK': 1411,
    'TL': 1318445,
    'TM': 6031200,
    'TN': 11818619,
    'TO': 105695,
    'TR': 84339067,
    'TT': 1399488,
    'TV': 11792,
    'TW': 23816775,
    'TZ': 59734218,
    'UA': 44134693,
    'UG': 45741000,
    'US': 331002647,
    'UY': 3473727,
    'UZ': 33469203,
    'VA': 801,
    'VC': 110947,
    'VE': 28435943,
    'VG': 30231,
    'VI': 104423,
    'VN': 97338583,
    'VU': 307145,
    'WF': 11239,
    'WS': 198410,
    'XK': 1831000,
    'YE': 29825968,
    'YT': 266150,
    'ZA': 59308690,
    'ZM': 18383956,
    'ZW': 14862927,
}
